package com.studioos.server.shared.enums;

public enum AuditEventType {
    MESSAGE_CREATED,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
    MESSAGE_REPORTED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    CONVERSATION_CREATED,
    ACTION_CREATED,
    TRANSACTION_CREATED,
    WALLET_UPDATED,
    ESCROW_CREATED,
    ESCROW_RELEASED,
    ESCROW_REFUNDED,
    TOPUP_REQUESTED
    ,PASSWORD_CHANGED
    ,EMAIL_CHANGED
    ,PHONE_CHANGED
    ,PROFILE_UPDATED
    ,USERNAME_CHANGED
    ,PROFILE_IMAGE_CHANGED
    ,PRIVACY_UPDATED
    ,ROLE_CHANGED
    ,ACCOUNT_DELETED
}
