package com.studioos.server.shared.enums;

public enum AuditEventType {
    MESSAGE_CREATED,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
    MESSAGE_REPORTED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    CONVERSATION_CREATED,
    ACTION_CREATED,
    TRANSACTION_CREATED,
    WALLET_UPDATED,
    ESCROW_CREATED,
    ESCROW_RELEASED,
    ESCROW_REFUNDED,
    TOPUP_REQUESTED
}