package com.studioos.server.shared.enums;

public enum SessionTimelineAction {
    SESSION_CREATED,
    ARTIST_CHECKED_IN,
    PRODUCER_CHECKED_IN,
    ENGINEER_CHECKED_IN,
    CHECKED_OUT,
    RECORDING_STARTED,
    RECORDING_PAUSED,
    RECORDING_RESUMED,
    RECORDING_FINISHED,
    MIXING_STARTED,
    MIXING_FINISHED,
    MASTERING_STARTED,
    MASTERING_FINISHED,
    REVISION_REQUESTED,
    REVISION_APPROVED,
    REVISION_REJECTED,
    REVISION_COMPLETED,
    DELIVERABLE_UPLOAD_CREATED,
    DELIVERABLE_UPLOAD_COMPLETED,
    DELIVERABLE_PROCESSING_STARTED,
    DELIVERABLE_PROCESSING_COMPLETED,
    DELIVERABLE_PROCESSING_FAILED,
    SESSION_COMPLETED,
    SESSION_CANCELLED,
    NO_SHOW_MARKED
}
